// <auto-generated />
using System;
using ExamManager.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExamManager.Repository.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210908201513_initPredmeti")]
    partial class initPredmeti
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExamManager.Domain.DomainModel.Ispit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BrojNaTermin")
                        .HasColumnType("int");

                    b.Property<string>("KodNaPredmet")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("PolaganjeDo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PolaganjeOd")
                        .HasColumnType("datetime2");

                    b.Property<int>("VremetraenjeNaTerminVoMinuti")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KodNaPredmet");

                    b.ToTable("Ispiti");
                });

            modelBuilder.Entity("ExamManager.Domain.DomainModel.Predmet", b =>
                {
                    b.Property<string>("KodNaPredmet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ImeNaPredmet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Semestar")
                        .HasColumnType("int");

                    b.Property<string>("StudiskiCiklusId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("KodNaPredmet");

                    b.HasIndex("StudiskiCiklusId");

                    b.ToTable("Predmeti");

                    b.HasData(
                        new
                        {
                            KodNaPredmet = "F18L1W005",
                            ImeNaPredmet = "Бизнис и менаџмент",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L1W007",
                            ImeNaPredmet = "Вовед во компјутерските науки",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L1S013",
                            ImeNaPredmet = "Калкулус",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L1W018",
                            ImeNaPredmet = "Професионални вештини",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L1W020",
                            ImeNaPredmet = "Структурно програмирање",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L1W031",
                            ImeNaPredmet = "Дискретни структури 1",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L1W033",
                            ImeNaPredmet = "Калкулус 1",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L1W041",
                            ImeNaPredmet = "Дизајн на дигитални кола",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L1W049",
                            ImeNaPredmet = "Физика",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L1W070",
                            ImeNaPredmet = "Педагогија",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L1W011",
                            ImeNaPredmet = "Дискретна математика",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L1S045",
                            ImeNaPredmet = "Компјутерски архитектури",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L1S016",
                            ImeNaPredmet = "Објектно-ориентирано програмирање",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L1S066",
                            ImeNaPredmet = "Основи на сајбер безбедноста",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L1S023",
                            ImeNaPredmet = "Бизнис статистика",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L1S032",
                            ImeNaPredmet = "Дискретни структури 2",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L1S034",
                            ImeNaPredmet = "Калкулус 2",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L1S116",
                            ImeNaPredmet = "Компјутерски компоненти",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L1S120",
                            ImeNaPredmet = "Креативни вештини за решавање проблеми",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L1S026",
                            ImeNaPredmet = "Маркетинг",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L1S015",
                            ImeNaPredmet = "Објектно ориентирана анализа и дизајн",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L1S052",
                            ImeNaPredmet = "ИТ системи за учење",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L1S003",
                            ImeNaPredmet = "Архитектура и организација на компјутери",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L1S146",
                            ImeNaPredmet = "Основи на веб дизајн",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L2W014",
                            ImeNaPredmet = "Компјутерски мрежи и безбедност",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L2W001",
                            ImeNaPredmet = "Алгоритми и податочни структури",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3W055",
                            ImeNaPredmet = "Мултимедијални технологии",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L2W046",
                            ImeNaPredmet = "Компјутерски мрежи",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L2W067",
                            ImeNaPredmet = "Основи на теоријата на информации",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L2W104",
                            ImeNaPredmet = "Инженерска математика",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L2W109",
                            ImeNaPredmet = "Интернет програмирање на клиентска страна",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L2W140",
                            ImeNaPredmet = "Напредно програмирање",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L2W006",
                            ImeNaPredmet = "Веројатност и статистика",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L2W096",
                            ImeNaPredmet = "Дигитизација",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L2W167",
                            ImeNaPredmet = "Шаблони за дизајн на кориснички интерфејси",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L2W147",
                            ImeNaPredmet = "Основи на комуникациски системи",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L2S100",
                            ImeNaPredmet = "Економија за ИКТ инженери",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L2W165",
                            ImeNaPredmet = "Управување со техничката поддршка",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L2S061",
                            ImeNaPredmet = "Безжични и мобилни системи",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L2S017",
                            ImeNaPredmet = "Оперативни системи",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L2S030",
                            ImeNaPredmet = "Вештачка интелигенција",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L2S082",
                            ImeNaPredmet = "Визуелно програмирање",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L2S084",
                            ImeNaPredmet = "Вовед во екоинформатиката",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L2S090",
                            ImeNaPredmet = "Вовед во случајни процеси",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L2S110",
                            ImeNaPredmet = "Интернет технологии",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L2S124",
                            ImeNaPredmet = "Медиуми и комуникации",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L2S143",
                            ImeNaPredmet = "Одржливи и енергетски ефикасни компјутерски системи",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L2S097",
                            ImeNaPredmet = "Дизајн на алгоритми",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L2S099",
                            ImeNaPredmet = "Е-влада",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L2S042",
                            ImeNaPredmet = "Електрични кола",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L2S114",
                            ImeNaPredmet = "Компјутерска графика",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S162",
                            ImeNaPredmet = "Споделување и пресметување во толпа",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L2S051",
                            ImeNaPredmet = "ИКТ во образованието",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L2S002",
                            ImeNaPredmet = "Анализа на софтверските барања",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L2S095",
                            ImeNaPredmet = "Дигитално процесирање на слика",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L2S164",
                            ImeNaPredmet = "Теорија на информации со дигитални комуникации",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L2S119",
                            ImeNaPredmet = "Концепти на информатичко општество",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L2S029",
                            ImeNaPredmet = "Софтверско инженерство",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3W060",
                            ImeNaPredmet = "Администрација на системи",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3W004",
                            ImeNaPredmet = "Бази на податоци",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3W065",
                            ImeNaPredmet = "Мрежна безбедност",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3W024",
                            ImeNaPredmet = "Веб програмирање",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3W081",
                            ImeNaPredmet = "Визуелизација",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3W008",
                            ImeNaPredmet = "Вовед во науката за податоци",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3W043",
                            ImeNaPredmet = "Информациска безбедност",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3W053",
                            ImeNaPredmet = "Компјутерска етика",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3W115",
                            ImeNaPredmet = "Компјутерски звук, говор и музика",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3W035",
                            ImeNaPredmet = "Линеарна алгебра и примени",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3W134",
                            ImeNaPredmet = "Мултимедиски мрежи",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3W148",
                            ImeNaPredmet = "Основи на роботиката",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3W050",
                            ImeNaPredmet = "Дизајн на образовен софтвер",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3W009",
                            ImeNaPredmet = "Дизајн и архитектура на софтвер",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3W044",
                            ImeNaPredmet = "Компјутерска електроника",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3W136",
                            ImeNaPredmet = "Напреден веб дизајн",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3W037",
                            ImeNaPredmet = "Паралелно и дистрибуирано процесирање",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S059",
                            ImeNaPredmet = "Администрација на мрежи",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S062",
                            ImeNaPredmet = "Виртуелизација",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S073",
                            ImeNaPredmet = "Агентно-базирани системи",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S077",
                            ImeNaPredmet = "Безжични мултимедиски системи",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S040",
                            ImeNaPredmet = "Вградливи микропроцесорски системи",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S087",
                            ImeNaPredmet = "Вовед во мрежна наука",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S093",
                            ImeNaPredmet = "Дигитална форензика",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S010",
                            ImeNaPredmet = "Дизајн на интеракцијата човек-компјутер",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S025",
                            ImeNaPredmet = "Електронска и мобилна трговија",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S111",
                            ImeNaPredmet = "Инфраструктурно програмирање",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S118",
                            ImeNaPredmet = "Континуирана интеграција и испорака",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S122",
                            ImeNaPredmet = "Криптографија",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S125",
                            ImeNaPredmet = "Мерење и анализа на интернет сообраќај",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S135",
                            ImeNaPredmet = "Мултимедиски системи",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S155",
                            ImeNaPredmet = "Сервисно ориентирани архитектури",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S159",
                            ImeNaPredmet = "Софтверски дефинирана безбедност",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S056",
                            ImeNaPredmet = "Персонализирано учење",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S071",
                            ImeNaPredmet = "Психологија на училишна возраст",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S057",
                            ImeNaPredmet = "Работа со надарени ученици",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S094",
                            ImeNaPredmet = "Дигитални библиотеки",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S019",
                            ImeNaPredmet = "Софтверски квалитет и тестирање",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S036",
                            ImeNaPredmet = "Машинско учење",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S039",
                            ImeNaPredmet = "Формални јазици и автомати",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S012",
                            ImeNaPredmet = "Интегрирани системи",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S149",
                            ImeNaPredmet = "Паралелно програмирање",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S150",
                            ImeNaPredmet = "Податочно рударство",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S047",
                            ImeNaPredmet = "Процесирање на сигналите",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S158",
                            ImeNaPredmet = "Современи компјутерски архитектури",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S163",
                            ImeNaPredmet = "Статистичко моделирање",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S153",
                            ImeNaPredmet = "Процесна роботика",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S166",
                            ImeNaPredmet = "Учење на далечина",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3W064",
                            ImeNaPredmet = "Дистрибуирани системи",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3W068",
                            ImeNaPredmet = "Пресметување во облак",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3W074",
                            ImeNaPredmet = "Администрација на бази на податоци",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3W075",
                            ImeNaPredmet = "Анализа и дизајн на ИС",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3W079",
                            ImeNaPredmet = "Веб базирани системи",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3W085",
                            ImeNaPredmet = "Вовед во биоинформатиката",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3W088",
                            ImeNaPredmet = "Вовед во паметни градови",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3W092",
                            ImeNaPredmet = "Дигитална постпродукција",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3W098",
                            ImeNaPredmet = "Дистрибуирано складирање на податоци",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3W103",
                            ImeNaPredmet = "Имплементација на системи со слободен и отворен код",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3W105",
                            ImeNaPredmet = "Иновации во ИКТ",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3W123",
                            ImeNaPredmet = "Машинска визија",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3W126",
                            ImeNaPredmet = "Методологија на истражувањето во ИКТ",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3W128",
                            ImeNaPredmet = "Мобилни информациски системи",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3W129",
                            ImeNaPredmet = "Мобилни платформи и програмирање",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3W133",
                            ImeNaPredmet = "Мрежна и мобилна форензика",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3W145",
                            ImeNaPredmet = "Оптички мрежи",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3W108",
                            ImeNaPredmet = "Интернет на нештата",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3W137",
                            ImeNaPredmet = "Напредна интеракција човек компјутер",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3W152",
                            ImeNaPredmet = "Програмирање на видео игри",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3W161",
                            ImeNaPredmet = "Социјални мрежи и медиуми",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3W038",
                            ImeNaPredmet = "Програмски парадигми",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3W072",
                            ImeNaPredmet = "Автономна роботика",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3W076",
                            ImeNaPredmet = "Вовед во анализа на временските серии",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3W089",
                            ImeNaPredmet = "Вовед во препознавање на облици",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3W131",
                            ImeNaPredmet = "Моделирање и симулација",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3W142",
                            ImeNaPredmet = "Обработка на природните јазици",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3W144",
                            ImeNaPredmet = "Операциони истражувања",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3W154",
                            ImeNaPredmet = "Рударење на масивни податоци",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3W156",
                            ImeNaPredmet = "Системи за поддршка при одлучувањето",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3W117",
                            ImeNaPredmet = "Компјутерски поддржано производство",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3W027",
                            ImeNaPredmet = "Менаџмент информациски системи",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3W048",
                            ImeNaPredmet = "Софтвер за вградливи системи",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3W160",
                            ImeNaPredmet = "Софтверски дефинирани мрежи",
                            Semestar = 0,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S063",
                            ImeNaPredmet = "Дизајн на компјутерски мрежи",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S121",
                            ImeNaPredmet = "Блоковски вериги и криптовалути",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S080",
                            ImeNaPredmet = "Веб пребарувачки системи",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S091",
                            ImeNaPredmet = "Географски информациски системи",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S101",
                            ImeNaPredmet = "Етичко хакирање",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S107",
                            ImeNaPredmet = "Интелигентни системи",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S127",
                            ImeNaPredmet = "Мобилни апликации",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S130",
                            ImeNaPredmet = "Моделирање и менаџирање на бизнис процеси",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S132",
                            ImeNaPredmet = "Модерни трендови во роботика",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S138",
                            ImeNaPredmet = "Напредни бази на податоци",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S139",
                            ImeNaPredmet = "Напредни теми од криптографија",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S141",
                            ImeNaPredmet = "Неструктурирани бази на податоци",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S028",
                            ImeNaPredmet = "Претприемништво",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S157",
                            ImeNaPredmet = "Складови на податоци и аналитичка обработка",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S022",
                            ImeNaPredmet = "Управување со ИКТ проекти",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S083",
                            ImeNaPredmet = "Виртуелна реалност",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S086",
                            ImeNaPredmet = "Вовед во когнитивни науки",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S113",
                            ImeNaPredmet = "Компјутерска анимација",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S07",
                            ImeNaPredmet = "Биолошки инспирирано пресметување",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S102",
                            ImeNaPredmet = "ИКТ за развој",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S106",
                            ImeNaPredmet = "Интелигентни информациски системи",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S151",
                            ImeNaPredmet = "Пресметковна биологија",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        },
                        new
                        {
                            KodNaPredmet = "F18L3S112",
                            ImeNaPredmet = "Програмски јазици и компајлери",
                            Semestar = 1,
                            StudiskiCiklusId = "Додипломски"
                        });
                });

            modelBuilder.Entity("ExamManager.Domain.DomainModel.PredmetOdStudiskaPrograma", b =>
                {
                    b.Property<string>("KodNaPredmet")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ImeNaStudiskaPrograma")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("KodNaPredmet", "ImeNaStudiskaPrograma");

                    b.HasIndex("ImeNaStudiskaPrograma");

                    b.ToTable("PredmetiOdStudiskaPrograma");
                });

            modelBuilder.Entity("ExamManager.Domain.DomainModel.Prostorija", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kapacitet")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Prostorii");
                });

            modelBuilder.Entity("ExamManager.Domain.DomainModel.Sproveduvac", b =>
                {
                    b.Property<string>("SproveduvacId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ImePrezime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SproveduvacId");

                    b.ToTable("Sproveduvaci");
                });

            modelBuilder.Entity("ExamManager.Domain.DomainModel.Student", b =>
                {
                    b.Property<int>("BrojNaIndeks")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImePrezime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TerminId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BrojNaIndeks");

                    b.HasIndex("TerminId");

                    b.ToTable("Studenti");
                });

            modelBuilder.Entity("ExamManager.Domain.DomainModel.StudentPolagaPredmet", b =>
                {
                    b.Property<int>("BrojNaIndeks")
                        .HasColumnType("int");

                    b.Property<string>("KodNaPredmet")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("BrojNaIndeks", "KodNaPredmet");

                    b.HasIndex("KodNaPredmet");

                    b.ToTable("StudentiPolagaatPredmeti");
                });

            modelBuilder.Entity("ExamManager.Domain.DomainModel.StudiskaPrograma", b =>
                {
                    b.Property<string>("ImeNaStudiskaPrograma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ImeNaStudiskaPrograma");

                    b.ToTable("StudiskiProgrami");

                    b.HasData(
                        new
                        {
                            ImeNaStudiskaPrograma = "Интернет мрежи и безбедност"
                        },
                        new
                        {
                            ImeNaStudiskaPrograma = "Компјутерска едукација"
                        },
                        new
                        {
                            ImeNaStudiskaPrograma = "Компјутерски науки"
                        },
                        new
                        {
                            ImeNaStudiskaPrograma = "Компјутерско инженерство"
                        },
                        new
                        {
                            ImeNaStudiskaPrograma = "Примена на информациски технологии"
                        },
                        new
                        {
                            ImeNaStudiskaPrograma = "Софтверско инженерство и информациски системи"
                        },
                        new
                        {
                            ImeNaStudiskaPrograma = "Software engineering and information systems"
                        },
                        new
                        {
                            ImeNaStudiskaPrograma = "Професионални студии по информатички технологии"
                        },
                        new
                        {
                            ImeNaStudiskaPrograma = "Професионални студии по информатика"
                        },
                        new
                        {
                            ImeNaStudiskaPrograma = "Академски студии по информатика"
                        },
                        new
                        {
                            ImeNaStudiskaPrograma = "Информатика и компјутерско инженерство"
                        },
                        new
                        {
                            ImeNaStudiskaPrograma = "Компјутерска едукација-стара"
                        },
                        new
                        {
                            ImeNaStudiskaPrograma = "Мрежни технологии"
                        },
                        new
                        {
                            ImeNaStudiskaPrograma = "Примена на е-технологии"
                        },
                        new
                        {
                            ImeNaStudiskaPrograma = "Компјутерски науки и инженерство"
                        });
                });

            modelBuilder.Entity("ExamManager.Domain.DomainModel.StudiskiCiklus", b =>
                {
                    b.Property<string>("CiklusNaStudii")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CiklusNaStudii");

                    b.ToTable("StudickiCiklusi");

                    b.HasData(
                        new
                        {
                            CiklusNaStudii = "Додипломски"
                        },
                        new
                        {
                            CiklusNaStudii = "Магистерски"
                        },
                        new
                        {
                            CiklusNaStudii = "Докторски"
                        });
                });

            modelBuilder.Entity("ExamManager.Domain.DomainModel.Termin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ispitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProstorijaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SproveduvacId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("VremeNaZapocnuvanje")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VremeNaZavrshuvanje")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ispitId");

                    b.HasIndex("ProstorijaId");

                    b.HasIndex("SproveduvacId")
                        .IsUnique()
                        .HasFilter("[SproveduvacId] IS NOT NULL");

                    b.ToTable("Termini");
                });

            modelBuilder.Entity("ExamManager.Domain.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("ExamManager.Domain.DomainModel.Ispit", b =>
                {
                    b.HasOne("ExamManager.Domain.DomainModel.Predmet", "IspitPoPredmet")
                        .WithMany("IspitiPoPredmet")
                        .HasForeignKey("KodNaPredmet");
                });

            modelBuilder.Entity("ExamManager.Domain.DomainModel.Predmet", b =>
                {
                    b.HasOne("ExamManager.Domain.DomainModel.StudiskiCiklus", "StudiskiCiklus")
                        .WithMany("PredmetiOdStudiskiCiklus")
                        .HasForeignKey("StudiskiCiklusId");
                });

            modelBuilder.Entity("ExamManager.Domain.DomainModel.PredmetOdStudiskaPrograma", b =>
                {
                    b.HasOne("ExamManager.Domain.DomainModel.StudiskaPrograma", "StudiskaPrograma")
                        .WithMany("PredmetiOdStudiskaPrograma")
                        .HasForeignKey("ImeNaStudiskaPrograma")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamManager.Domain.DomainModel.Predmet", "Predmet")
                        .WithMany("PredmetOdStudiskiProgrami")
                        .HasForeignKey("KodNaPredmet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExamManager.Domain.DomainModel.Student", b =>
                {
                    b.HasOne("ExamManager.Domain.DomainModel.Termin", "StudentPolagaVoTermin")
                        .WithMany("StudentiPolagaatVoTermin")
                        .HasForeignKey("TerminId");
                });

            modelBuilder.Entity("ExamManager.Domain.DomainModel.StudentPolagaPredmet", b =>
                {
                    b.HasOne("ExamManager.Domain.DomainModel.Student", "Student")
                        .WithMany("StudentPolagaPredmeti")
                        .HasForeignKey("BrojNaIndeks")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamManager.Domain.DomainModel.Predmet", "Predmet")
                        .WithMany("StudentiKoiPolagaatPredmet")
                        .HasForeignKey("KodNaPredmet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExamManager.Domain.DomainModel.Termin", b =>
                {
                    b.HasOne("ExamManager.Domain.DomainModel.Ispit", "TerminVoKojSePolagaIspit")
                        .WithMany("IspitSePolagaVoTermini")
                        .HasForeignKey("ispitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamManager.Domain.DomainModel.Prostorija", "TerminSeRealiziraVoProstija")
                        .WithMany("ProstijaVoKojaSeRealiziraTermin")
                        .HasForeignKey("ProstorijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamManager.Domain.DomainModel.Sproveduvac", "DezurenSproveduvacVoTermin")
                        .WithOne("SproveduvacDezuraVoTermin")
                        .HasForeignKey("ExamManager.Domain.DomainModel.Termin", "SproveduvacId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ExamManager.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ExamManager.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamManager.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ExamManager.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
